<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="osgi" nsURI="platform:/plugin/no.hal.osgi.emf/model/osgi.ecore"
    nsPrefix="osgiEmf">
  <eClassifiers xsi:type="ecore:EClass" name="Manifest" eSuperTypes="#//GenericAttributesContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="#//Version"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericAttributesContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericAttributes" upperBound="-1"
        eType="#//GenericAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//GenericAttributeValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extraAttributes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Version" instanceClassName="no.hal.osgi.emf.util.Version"/>
  <eClassifiers xsi:type="ecore:EDataType" name="VersionRange" instanceClassName="no.hal.osgi.emf.util.VersionRange"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bundle" eSuperTypes="#//GenericAttributesContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manifestVersion" eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbolicName" eType="#//QualifiedName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleton" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vendor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activator" eType="#//QualifiedName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classPath" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredExecutionEnvironment"
        upperBound="-1" eType="#//RequiredExecutionEnvironmentKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activationPolicy" eType="#//ActivationPolicyKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exportPackage" upperBound="-1"
        eType="#//ExportedPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importPackage" upperBound="-1"
        eType="#//ImportedPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requireBundle" upperBound="-1"
        eType="#//RequiredBundle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceComponent" upperBound="-1"
        eType="#//ServiceComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RequiredExecutionEnvironmentKind">
    <eLiterals name="default" literal="default"/>
    <eLiterals name="Java4" value="4" literal="J2SE-1.4"/>
    <eLiterals name="Java5" value="5" literal="J2SE-1.5"/>
    <eLiterals name="Java6" value="6" literal="JavaSE-1.6"/>
    <eLiterals name="Java7" value="7" literal="JavaSE-1.7"/>
    <eLiterals name="Java8" value="8" literal="JavaSE-1.8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivationPolicyKind">
    <eLiterals name="default" literal="default"/>
    <eLiterals name="lazy" value="1" literal="lazy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredBundle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//QualifiedName"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleVersion" eType="#//VersionRange"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//VisibilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvesTo" upperBound="-1"
        eType="#//Bundle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisibilityKind">
    <eLiterals name="default" literal="default"/>
    <eLiterals name="reexport" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BundlePackage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//QualifiedName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="QualifiedName" instanceClassName="no.hal.osgi.emf.util.QualifiedName"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExportedPackage" eSuperTypes="#//BundlePackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="#//Version"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportedPackage" eSuperTypes="#//BundlePackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="#//VersionRange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvesTo" upperBound="-1"
        eType="#//Bundle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="#//Path"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="ecore:EClass scr-1.2.0.ecore#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Path" instanceClassName="no.hal.osgi.emf.util.Path"/>
</ecore:EPackage>
